name: 404 Page Not Found Report
description: Report a 404 Page Not Found Error, 
title: "[404]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: origin
    attributes:
      label: From where did you get linked to the 404 ?
      description: If it was the Wiki, please include Chapter and section.
      placeholder: 
      value: 
    validations:
      required: true
  - type: textarea
    id: target
    attributes:
      label: Please post the link that showed you the 404 Error
      description: This is required so we can add automated redirects to either the main page or the intended section.
      placeholder: 
      value: 
    validations:
      required: true
