name: 404 Page Not Found Report
description: Report a 404 Page Not Found Error
title: "Not found Report Issue"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report the issue!
  - type: textarea
    id: origin_link
    attributes:
      label: From what page did you get linked to the 404 ?
      description: Please post the link to the page where you were linked to the not found page.
      placeholder: https://www.bad-link-in-wiki-does-not-work.org/
      value: 
    validations:
      required: true
  - type: textarea
    id: origin_chapter
    attributes:
      label: If it was in the Wiki, where on the page did you get linked to the error ?
      description: Please describe the position good enough, so that we can find the link and fix it.
      placeholder: 'The link can be found when seaching for the word "foo"'
    validations:
      required: false
  - type: textarea
    id: target
    attributes:
      label: Please post the link that showed you the 404 Error
      description: This is required so we can add automated redirects to either the main page or the intended section.
      placeholder: https://www.bad-link-does-not-work.org/
      value: 
    validations:
      required: true
