[book]
authors = ["Wabbajack Team"]
language = "en"
multilingual = false
src = "src"
title = "Wabbajack Documentation"
description = "The Official Wabbajack Documentation."

[build]
create-missing = false
extra-watch-dirs = ["../"]

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"